#配置数据库的连接信息
spring:
  application:
      name: tlias-web-management
  #配置数据库的连接信息
  datasource:
      url: jdbc:mysql://localhost:3306/tlias
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: xirxil99
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小
      max-request-size: 100MB

#MyBatis配置
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #驼峰命名
      map-underscore-to-camel-case: true


#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-web-mpl
    region: cn-beijing